name: Docker Build, Push, and Deploy

on:
  push:
    branches: [main]

env:
  DOCKERHUB_USERNAME: tejpatel595
  IMAGE_NAME: testing-ups

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/testing-ups:${{ github.sha }}

  deploy:
    needs: [build-and-push]
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Docker
      uses: docker/deploy-action@v1
      with:
        image: ${{ secrets.DOCKERHUB_USERNAME }}/testing-ups:${{ github.sha }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
